spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/theater
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
    generate-ddl: false

  flyway:
    baseline-on-migrate: true
    baseline-version: 0
    enabled: true

#logging:
#  level:
#    org.hibernate.SQL: debug
